robotino:
    actor_alpha: 0.0003 #0.0003
    critic_alpha: 0.0003
    gamma: 0.99
    tau: 0.005 #0.005 #0.01
    nepisodes: 3000
    nsteps: 250
    stage_name: "training"
    fsnepisodes: 3000
    # stage_name: "turtlebot3_top_8_obstacle" # "revamped/new_tracking_cp_gcp_nobonus_corrected_3_no_cpdto"